# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ruby/install:
          version: "$(cat .ruby-version)"
      - ruby/install-deps:
          key: gems-v1
      - run:
          name: Set up Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: CC test reporter - before build
          command: ./cc-test-reporter before-build
      - ruby/rspec-test
      - run:
          name: CC test reporter - after build
          command: |
            ./cc-test-reporter after-build --coverage-input-type simplecov

workflows:
  test:
    jobs:
      - rspec
