# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  code-climate: travelaudience/code-climate@0.1.5
  ruby: circleci/ruby@1.8.0

jobs:
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ruby/install:
          version: "$(cat .ruby-version)"
      - code-climate/install
      - ruby/install-deps:
          key: gems-v1
      - ruby/rspec-test
      - code-climate/format_coverage:
          coverage_file: coverage/coverage.json
          input_type: simplecov
      - code-climate/upload_coverage

workflows:
  test:
    jobs:
      - rspec
