# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0


jobs:
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: "`$(cat .ruby-version)`"
      - ruby/install-deps:
          key: gems-v1
      - ruby/rspec-test

workflows:
  test:
    jobs:
      - rspec
